// @ts-check

import { Select, Button, TextField } from './lib/inputs.js';

/**
 * @typedef DrawingTableRow
 * @property {number} machine
 * @property {'DISC'|'DRUM'} brakeType
 * @property {string} motorFrame
 * @property {string} manufacturer
 * @property {number} dimA
 * @property {number} dimB
 * @property {number} dimC
 * @property {number|null} dimL
 * @property {number} dimW
 * @property {number} item1Qty
 * @property {string} item1Part
 * @property {string} item1Desc
 * @property {number|null} item2Qty
 * @property {string|null} item2Part
 * @property {string|null} item2Desc
 * @property {number|null} item3Qty
 * @property {string|null} item3Part
 * @property {string|null} item3Desc
 * @property {number} finish
 * @property {string|null} notes
 */

/** @type {DrawingTableRow[]} */
const drawingTable = [
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '215T',
    manufacturer: 'IMP',
    dimA: 24.063,
    dimB: 1,
    dimC: 2,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 5.4# X 12',
    item3Desc: 'CHANNEL, 12" LONG',
    finish: 1.625,
    notes: null,
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '254T',
    manufacturer: 'IMP',
    dimA: 25.938,
    dimB: 2.125,
    dimC: 3,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.75 X 4 X 14.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '256T',
    manufacturer: 'IMP',
    dimA: 26.938,
    dimB: 3,
    dimC: 3,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.75 X 4 X 14.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 27.813,
    dimB: 2.75,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.125,
    notes: 'STD BASE ONLY',
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 27.813,
    dimB: 2.75,
    dimC: 7.5,
    dimL: null,
    dimW: 4,
    item1Qty: 2,
    item1Part: '0.625 X 4 X 15',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.125,
    notes: 'RG MTG ONLY',
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 28.563,
    dimB: 3.5,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.125,
    notes: 'STD BASE ONLY',
  },
  {
    machine: 34,
    brakeType: 'DISC',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 28.563,
    dimB: 3.5,
    dimC: 7.5,
    dimL: null,
    dimW: 4,
    item1Qty: 2,
    item1Part: '0.625 X 4 X 15',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.125,
    notes: 'RG MTG ONLY',
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '215T',
    manufacturer: 'IMP',
    dimA: 27.75,
    dimB: 1.5,
    dimC: 2.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 12.5',
    item3Desc: 'SHIP CHANNEL, 12.5" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '254T',
    manufacturer: 'IMP',
    dimA: 29.75,
    dimB: 2.125,
    dimC: 3,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 5.4# X 14',
    item3Desc: 'CHANNEL, 14" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '256T',
    manufacturer: 'IMP',
    dimA: 30.625,
    dimB: 3,
    dimC: 3,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 5.4# X 14',
    item3Desc: 'CHANNEL, 14" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 31.5,
    dimB: 2.75,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '1 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 15.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 32.25,
    dimB: 3.5,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '1 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 15.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 33.125,
    dimB: 2.75,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 43,
    brakeType: 'DRUM',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 33.875,
    dimB: 3.5,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '215T',
    manufacturer: 'IMP',
    dimA: 27.938,
    dimB: 1.5,
    dimC: 2.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 12.5',
    item3Desc: 'SHIP CHANNEL, 12.5" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '254T',
    manufacturer: 'IMP',
    dimA: 29.938,
    dimB: 1.625,
    dimC: 3,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.625 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 14',
    item3Desc: 'CHANNEL, 14" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '256T',
    manufacturer: 'IMP',
    dimA: 30.813,
    dimB: 2.5,
    dimC: 3,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.625 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 14',
    item3Desc: 'CHANNEL, 14" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 31.688,
    dimB: 2.75,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '1 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 15.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 32.438,
    dimB: 3.5,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '1 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 15.5',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.625,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 33.313,
    dimB: 2.75,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 44,
    brakeType: 'DISC',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 34.063,
    dimB: 3.5,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: null,
    item2Part: null,
    item2Desc: null,
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '254T',
    manufacturer: 'IMP',
    dimA: 1,
    dimB: 0.5,
    dimC: 2.625,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 13.25',
    item3Desc: 'SHIP CHANNEL, 13.25" LONG',
    finish: 3.125,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '256T',
    manufacturer: 'IMP',
    dimA: 1.75,
    dimB: 1.25,
    dimC: 2.625,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 13.25',
    item3Desc: 'SHIP CHANNEL, 13.25" LONG',
    finish: 3.125,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 33.563,
    dimB: 2.75,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 15',
    item3Desc: 'SHIP CHANNEL, 15" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 34.438,
    dimB: 3.5,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 15',
    item3Desc: 'SHIP CHANNEL, 15" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 35.313,
    dimB: 2.75,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 17',
    item3Desc: 'CHANNEL, 17" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 36.063,
    dimB: 3.5,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 17',
    item3Desc: 'CHANNEL, 17" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '364T',
    manufacturer: 'IMP',
    dimA: 36.938,
    dimB: 4.125,
    dimC: 5.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 19',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 53,
    brakeType: 'DRUM',
    motorFrame: '365T',
    manufacturer: 'IMP',
    dimA: 37.438,
    dimB: 4.625,
    dimC: 5.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 19',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '254T',
    manufacturer: 'IMP',
    dimA: 30.125,
    dimB: 0.5,
    dimC: 2.625,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 13.25',
    item3Desc: 'SHIP CHANNEL, 13.25" LONG',
    finish: 3.125,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '256T',
    manufacturer: 'IMP',
    dimA: 31.0,
    dimB: 1.25,
    dimC: 2.625,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 13.25',
    item3Desc: 'SHIP CHANNEL, 13.25" LONG',
    finish: 3.125,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '284T',
    manufacturer: 'IMP',
    dimA: 31.75,
    dimB: 2.75,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 15',
    item3Desc: 'SHIP CHANNEL, 15" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '286T',
    manufacturer: 'IMP',
    dimA: 32.625,
    dimB: 3.5,
    dimC: 3.5,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.875 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 4',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '4 X 13.8# X 15',
    item3Desc: 'SHIP CHANNEL, 15" LONG',
    finish: 2.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 33.5,
    dimB: 2.75,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 17',
    item3Desc: 'CHANNEL, 17" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 34.25,
    dimB: 3.5,
    dimC: 4.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.625 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 17',
    item3Desc: 'CHANNEL, 17" LONG',
    finish: 1.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '364T',
    manufacturer: 'IMP',
    dimA: 35.125,
    dimB: 4.125,
    dimC: 5.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 19',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 54,
    brakeType: 'DISC',
    motorFrame: '365T',
    manufacturer: 'IMP',
    dimA: 35.625,
    dimB: 4.625,
    dimC: 5.25,
    dimL: 4,
    dimW: 4,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 4',
    item1Desc: 'STEEL PLATE',
    item2Qty: 2,
    item2Part: '0.625 X 4 X 19',
    item2Desc: 'STEEL PLATE',
    item3Qty: null,
    item3Part: null,
    item3Desc: null,
    finish: 0.375,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 40.125,
    dimB: 2.75,
    dimC: 4.5,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 17',
    item3Desc: 'SHIP CHANNEL, 17" LONG',
    finish: 3.25,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 40.875,
    dimB: 3.5,
    dimC: 4.5,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 17',
    item3Desc: 'SHIP CHANNEL, 17" LONG',
    finish: 3.25,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '364T',
    manufacturer: 'IMP',
    dimA: 41.75,
    dimB: 4.125,
    dimC: 5.25,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 12.0# X 18.5',
    item3Desc: 'SHIP CHANNEL, 18.5" LONG',
    finish: 2.25,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '365T',
    manufacturer: 'IMP',
    dimA: 42.25,
    dimB: 3.75,
    dimC: 5.25,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 12.0# X 18.5',
    item3Desc: 'SHIP CHANNEL, 18.5" LONG',
    finish: 2.25,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '404T',
    manufacturer: 'IMP',
    dimA: 44.375,
    dimB: 3.875,
    dimC: 6.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.5 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 21',
    item3Desc: 'CHANNEL, 21" LONG',
    finish: 1.25,
    notes: null,
  },
  {
    machine: 63,
    brakeType: 'DRUM',
    motorFrame: '405T',
    manufacturer: 'IMP',
    dimA: 45.125,
    dimB: 4.625,
    dimC: 6.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.5 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 21',
    item3Desc: 'CHANNEL, 21" LONG',
    finish: 1.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '324T',
    manufacturer: 'IMP',
    dimA: 35.625,
    dimB: 2.25,
    dimC: 4.5,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 17',
    item3Desc: 'SHIP CHANNEL, 17" LONG',
    finish: 3.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '326T',
    manufacturer: 'IMP',
    dimA: 36.375,
    dimB: 3,
    dimC: 4.5,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 17',
    item3Desc: 'SHIP CHANNEL, 17" LONG',
    finish: 3.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '364T',
    manufacturer: 'IMP',
    dimA: 37.25,
    dimB: 3.125,
    dimC: 5.25,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 12.0# X 18.5',
    item3Desc: 'SHIP CHANNEL, 18.5" LONG',
    finish: 2.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '365T',
    manufacturer: 'IMP',
    dimA: 37.75,
    dimB: 2.75,
    dimC: 5.25,
    dimL: 4,
    dimW: 6,
    item1Qty: 4,
    item1Part: '0.75 X 4 X 6',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 2.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 12.0# X 18.5',
    item3Desc: 'SHIP CHANNEL, 18.5" LONG',
    finish: 2.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '404T',
    manufacturer: 'IMP',
    dimA: 39.875,
    dimB: 3.875,
    dimC: 6.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.5 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 21',
    item3Desc: 'CHANNEL, 21" LONG',
    finish: 1.25,
    notes: null,
  },
  {
    machine: 64,
    brakeType: 'DISC',
    motorFrame: '405T',
    manufacturer: 'IMP',
    dimA: 40.625,
    dimB: 4.625,
    dimC: 6.5,
    dimL: 4,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.5 X 4 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 1.75 X 5',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '5 X 6.7# X 21',
    item3Desc: 'CHANNEL, 21" LONG',
    finish: 1.25,
    notes: null,
  },
  {
    machine: 74,
    brakeType: 'DRUM',
    motorFrame: '405T',
    manufacturer: 'IMP',
    dimA: 45.5,
    dimB: 3.875,
    dimC: 5.5,
    dimL: 5,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.875 X 5 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 21',
    item3Desc: 'SHIP CHANNEL, 21" LONG',
    finish: 2.875,
    notes: 'BS/OD MACHINE',
  },
  {
    machine: 74,
    brakeType: 'DRUM',
    motorFrame: '405T',
    manufacturer: 'IMP',
    dimA: 45.5,
    dimB: 3.875,
    dimC: 5.5,
    dimL: 5,
    dimW: 5,
    item1Qty: 4,
    item1Part: '0.75 X 5 X 5',
    item1Desc: 'STEEL PLATE',
    item2Qty: 4,
    item2Part: '0.125 X 3.5 X 6',
    item2Desc: 'STEEL PLATE',
    item3Qty: 2,
    item3Part: '6 X 15.3# X 21',
    item3Desc: 'SHIP CHANNEL, 21" LONG',
    finish: 2.875,
    notes: 'OH MACHINE',
  },
];

const machineBaseNames = [
  '34-OH-1',
  '34-OH-1-620',
  '34-OH-1-RT',
  '43-OH-1',
  '44-OH-1-620',
  '44-OH-1-622',
  '44-OH-1-RT',
  '53-OH-1',
  '54-OH-1-620',
  '54-OH-1-622',
  '54-OH-1-RT',
  '63-OH-1',
  '64-OH-1',
  '64-OH-1-622',
  '64-OH-1-626',
  '64-OH-1-RT',
  '74-OH-1',
  '74-OH-1-622',
  '74-OH-1-626',
  '74-OH-1-RT',
];

const motorFrameSelect = new Select('motor_frame');
const machineBaseModelSelect = new Select('machine_base_model');
const updateButton = new Button('update');
const motorManufacturerField = new TextField('motor_manufacturer');
const brakeTypeField = new TextField('brake_type');
const motorPadFinishField = new TextField('motor_pad_finish');

const motorPadBomQtyField1 = new TextField('motor_pad_bom_qty_1');
const motorPadBomQtyField2 = new TextField('motor_pad_bom_qty_2');
const motorPadBomQtyField3 = new TextField('motor_pad_bom_qty_3');
const motorPadBomPartNumField1 = new TextField('motor_pad_bom_part_num_1');
const motorPadBomPartNumField2 = new TextField('motor_pad_bom_part_num_2');
const motorPadBomPartNumField3 = new TextField('motor_pad_bom_part_num_3');
const motorPadBomDescField1 = new TextField('motor_pad_bom_desc_1');
const motorPadBomDescField2 = new TextField('motor_pad_bom_desc_2');
const motorPadBomDescField3 = new TextField('motor_pad_bom_desc_3');

const motorPadDimFieldA = new TextField('motor_pad_dim_a');
const motorPadDimFieldB = new TextField('motor_pad_dim_b');
const motorPadDimFieldC = new TextField('motor_pad_dim_c');
const motorPadDimFieldL = new TextField('motor_pad_dim_l');
const motorPadDimFieldW = new TextField('motor_pad_dim_w');
const motorPadNotes = new TextField('motor_pad_notes');

motorFrameSelect.value = '256T';
machineBaseModelSelect.value = '34-OH-1';

// const motorFrameSelect = this.getField('motor_frame');
// const machineBaseModelSelect = this.getField('machine_base_model');
// const updateButton = this.getField('update');
// const motorManufacturerField = this.getField('motor_manufacturer');
// const brakeTypeField = this.getField('brake_type');
// const motorPadFinishField = this.getField('motor_pad_finish');

// const motorPadBomQtyField1 = this.getField('motor_pad_bom_qty_1');
// const motorPadBomQtyField2 = this.getField('motor_pad_bom_qty_2');
// const motorPadBomQtyField3 = this.getField('motor_pad_bom_qty_3');
// const motorPadBomPartNumField1 = this.getField('motor_pad_bom_part_num_1');
// const motorPadBomPartNumField2 = this.getField('motor_pad_bom_part_num_2');
// const motorPadBomPartNumField3 = this.getField('motor_pad_bom_part_num_3');
// const motorPadBomDescField1 = this.getField('motor_pad_bom_desc_1');
// const motorPadBomDescField2 = this.getField('motor_pad_bom_desc_2');
// const motorPadBomDescField3 = this.getField('motor_pad_bom_desc_3');
// const motorPadDimFieldA = this.getField('motor_pad_dim_a');
// const motorPadDimFieldB = this.getField('motor_pad_dim_b');
// const motorPadDimFieldC = this.getField('motor_pad_dim_c');
// const motorPadDimFieldL = this.getField('motor_pad_dim_l');
// const motorPadDimFieldW = this.getField('motor_pad_dim_w');
// const motorPadNotes = this.getField('motor_pad_notes');

/**
 * @param {Record<string, any>[]} arr
 * @param {string} key
 */
function getOptions(arr, key) {
  const options = [];

  for (let i = 0; i < arr.length; i++) {
    const row = arr[i];
    if (options.indexOf(row[key]) > -1) continue;
    options.push(row[key]);
  }

  return options;
}

function populateDrawing() {
  const options = getOptions(drawingTable, 'motorFrame');
  motorFrameSelect.setItems(options);
  machineBaseModelSelect.setItems(machineBaseNames);
}

export function updateFields() {
  const frame = motorFrameSelect.value;
  const machineBase = machineBaseModelSelect.value;

  if (!frame || !machineBase) return;

  const [machineStr] = machineBase.split('-');
  const machineNum = parseInt(machineStr);

  /** @type { Omit<typeof drawingTable[number], 'machine' | 'motorFrame'> | undefined} */
  let findResult = undefined;

  for (let i = 0; i < drawingTable.length; i++) {
    const row = drawingTable[i];
    if (row.machine !== machineNum) continue;
    if (row.motorFrame !== frame) continue;
    findResult = row;
    break;
  }

  if (!findResult) return;

  const {
    brakeType,
    dimA,
    dimB,
    dimC,
    dimL,
    dimW,
    item1Desc,
    item1Part,
    item1Qty,
    item2Desc,
    item2Part,
    item2Qty,
    item3Desc,
    item3Part,
    item3Qty,
    finish,
    manufacturer,
    notes,
  } = findResult;

  motorManufacturerField.value = `${frame} ${manufacturer}`;
  brakeTypeField.value = brakeType;
  motorPadFinishField.value = `${finish}`;

  motorPadBomQtyField1.value = `${item1Qty}`;
  motorPadBomPartNumField1.value = item1Part;
  motorPadBomDescField1.value = item1Desc;

  motorPadBomQtyField2.value = item2Qty ? `${item2Qty}` : '';
  motorPadBomPartNumField2.value = item2Part ? item2Part : '';
  motorPadBomDescField2.value = item2Desc ? item2Desc : '';

  motorPadBomQtyField3.value = item3Qty ? `${item3Qty}` : '';
  motorPadBomPartNumField3.value = item3Part ? item3Part : '';
  motorPadBomDescField3.value = item3Desc ? item3Desc : '';

  motorPadDimFieldA.value = `${dimA}`;
  motorPadDimFieldB.value = `${dimB}`;
  motorPadDimFieldC.value = `${dimC}`;
  motorPadDimFieldL.value = dimL ? `${dimL}` : '';
  motorPadDimFieldW.value = dimW ? `${dimW}` : '';
  motorPadNotes.value = notes || '';

  console.table({
    motor_frame: frame,
    machine_base_model: machineBaseModelSelect.value,
  });

  console.table({
    brake_type: brakeTypeField.value,
    motor_manufacturer: motorManufacturerField.value,
    motor_pad_finish: motorPadFinishField.value,

    motor_pad_bom_qty_1: motorPadBomQtyField1.value,
    motor_pad_bom_qty_2: motorPadBomQtyField2.value,
    motor_pad_bom_qty_3: motorPadBomQtyField3.value,
    motor_pad_bom_part_num_1: motorPadBomPartNumField1.value,
    motor_pad_bom_part_num_2: motorPadBomPartNumField2.value,
    motor_pad_bom_part_num_3: motorPadBomPartNumField3.value,
    motor_pad_bom_desc_1: motorPadBomDescField1.value,
    motor_pad_bom_desc_2: motorPadBomDescField2.value,
    motor_pad_bom_desc_3: motorPadBomDescField3.value,

    motor_pad_dim_a: motorPadDimFieldA.value,
    motor_pad_dim_b: motorPadDimFieldB.value,
    motor_pad_dim_c: motorPadDimFieldC.value,
    motor_pad_dim_l: motorPadDimFieldL.value,
    motor_pad_dim_w: motorPadDimFieldW.value,

    notes: motorPadNotes.value,
  });
}

populateDrawing();

// updateFields();

updateButton.setAction('MouseUp', 'updateFields()');
